name: sapiency_app
description: Sapiency App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: 2.0.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # architecture
  flutter_hooks: 0.16.0
  provider: 5.0.0
  injector: 2.0.0
  freezed_annotation: 0.14.1
  flutter_sheet_localization: 5.1.0
  logger: 1.0.0
  json_annotation: 4.0.1
  equatable: 2.0.0

  # http
  chopper: 4.0.0-nullsafety.1

  # firebase
  firebase_core: ^1.1.0
  firebase_crashlytics: ^2.0.2
  firebase_storage: 8.0.2

  # misc widgets
  cached_network_image: ^2.5.1
  flutter_svg: 0.21.0+1
  pin_code_fields: 7.0.0
  page_transition: ^2.0.1-nullsafety.0
  keyboard_avoider: ^0.1.2
  flutter_keyboard_size: ^1.0.0+3
  image_picker: ^0.7.3
  flutter_spinkit: ^5.0.0
  readmore: ^2.0.0
  intl_phone_field:
    git:
      url: https://github.com/kalemba128/intl_phone_field.git
  webview_flutter: 2.0.4
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.4.0

  # misc utils
  easy_mask: ^1.1.5
  decimal: ^1.1.0
  intl: 0.17.0
  shared_preferences: 2.0.5
  uuid: 3.0.4
  email_validator: ^2.0.1
  duration: ^3.0.6
  url_launcher: ^6.0.3
  share: ^2.0.1
  clipboard: ^0.1.3


dev_dependencies:
  build_runner: 1.12.2
  freezed: 0.14.1+2
  flutter_sheet_localization_generator: 5.1.6
  json_serializable: 4.1.1
  chopper_generator: 4.0.0-nullsafety.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/flags/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/socials/

  fonts:
    - family: "Axiforma"
      fonts:
        - asset: fonts/Axiforma-Bold.ttf
          weight: 700
        - asset: fonts/Axiforma-Medium.ttf
          weight: 500
        - asset: fonts/Axiforma-Regular.ttf
          weight: 300
        - asset: fonts/Axiforma-Light.ttf
          weight: 100



flutter_intl:
  main_locale: pl
  enabled: true
